version: '3'

services:
  db:
    image: mongo:5.0.24
    container_name: chat_with_joy
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: chat-wth-joy
    volumes:
      - ./.mongo:/data/db